name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild Template_console_application_cpp.sln /p:Configuration=Release

      - name: Prepare Release Folder
        run: |
          mkdir release
          copy x64\Release\Template_console_application_cpp.exe release\Template_console_application_cpp.exe
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: release/
          
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-build/*
